plugins:
  discourse_vimeo_upload_enabled:
    default: true
    client: true
  vimeo_upload_enabled:
    default: false
    client: true
  vimeo_api_access_token:
    default: api_access_token
    client: true
  vimeo_default_view_privacy:
    default: anybody
    client: true
  vimeo_default_embed_privacy:
    default: public
    client: true
  youtube_upload_enabled:
    default: false
    client: true
  youtube_api_client_id:
    default: api_client_id
    client: true
  youtube_default_view_privacy:
    default: unlisted
    client: true
