plugins:
  discourse_vimeo_upload_enabled:
    default: true
    client: true
  vimeo_api_client_id:
    default: api_client_id
    client: true
  vimeo_api_client_key:
    default: api_client_key
    client: true
  vimeo_api_access_token:
    default: api_access_token
    client: true
